### ISSUE TITLE
something wrong during npm release ?

### ISSUE THREAD

**Issue by mamico** [vielhuber/chefcookie#9]
Looking at the latest version I can't find the latest changes (like location.host vs location.hostname):

```
$ cd /tmp
$ npm pack chefcookie
$ tar zxvf chefcookie-2.4.6.tgz
$ grep location.host package/_build/_helper.js 
      var host = window.location.host;
```
That's different from `var host = window.location.host;` https://github.com/vielhuber/chefcookie/blob/master/_js/_helper.js#L65

**Comment by vielhuber** [comment]
Strange, can you try again with 2.4.7?
